# Generated by Django 3.2.9 on 2021-12-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('sexo', models.CharField(choices=[('Femenino', 'femenino'), ('Masculino', 'masculino'), ('Otro', 'otro'), ('No definido', 'no_definido')], max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=30, verbose_name='Nombre completo')),
                ('state', models.BooleanField(default=True, verbose_name='Usuario Activado/Usuario no Activado')),
                ('fecha_usuario', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
